[project]
protostar-version = "0.9.1"
lib-path = "lib"

[contracts]
ex4 = ["contracts/ex4.cairo"]

[profile.testnet.project]
network="testnet"
private-key-path = "./.env"
account-address="0x03F878C94De81906ba1A016aB0E228D361753536681a776ddA29674FfeBB3CB0"